name: Pull request checks

on:
  pull_request

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: Assign
      run: |
        echo ${GITHUB_REPOSITORY}
        echo ${GITHUB_TRIGGERING_ACTOR}
        echo "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/1/assignees"
        echo "{\"assignees\":[\"${GITHUB_TRIGGERING_ACTOR}\"]}"
        curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${GITHUB_TOKEN}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/1/assignees" -d "{\"assignees\":[\"${GITHUB_TRIGGERING_ACTOR}\"]}"