name: Pull request checks

on: pull_request

permissions: write-all

env:
  pat: ${{ secrets.PAT }}

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Assign
        run: |
          curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${GITHUB_TOKEN}" https://api.github.com/repos/${GITHUB_REPOSITORY}/assignees
