name: Pull request checks

on:
  pull_request

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: Assign
      run: |
        curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${GITHUB_TOKEN}" https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/8/assignees -d '{"assignees":["${GITHUB_TRIGGERING_ACTOR}"]}'